# Generated by Django 5.0.7 on 2024-07-26 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_price_tag_product_available_product_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='prices',
        ),
        migrations.AddField(
            model_name='price',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.material'),
        ),
    ]
