# Generated by Django 5.0.7 on 2024-07-26 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_material_prices_price_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.material'),
        ),
    ]
