# Generated by Django 5.0.7 on 2024-07-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_price_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
